[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.98
option_as_alt = "Both"

[window.padding]
x = 5
y = 5

[env]
TERM = "xterm-256color"

[font]


[[keyboard.bindings]]
action = "ReceiveChar"
key = "F"
mods = "Command|Shift"

