[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.98
option_as_alt = "Both"

[window.padding]
x = 5
y = 5

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "F"
mods = "Command|Shift"

