arch = [
  "acpi",
  "base",
  "base-devel",
  "docker",
  "docker-compose",
  "dkms",
  "dmidecode",
  "dosfstools",
  "efibootmgr",
  "exfatprogs",
  "fish",
  "fisher",
  "git",
  "inetutils",
  "libgsf",
  "linux",
  "linux-firmware",
  "linux-headers",
  "man-db",
  "metapac",
  "nfs-utils",
  "nano",
  "sops",
  "net-tools",
  "ntp",
  "nvme-cli",
  "openvpn",
  "plocate",
  "pacman-contrib",
  "python-pynvim",
  "qt6-imageformats",
  "reflector",
  "smartmontools",
  "sshfs",
  "sudo",
  "traceroute",
  "unrar",
  "usbutils",
  "veracrypt",
  "vim",
  "wget",
  "whois",
  "wireless-regdb",
  "wireless_tools",
  "yay",
  "zram-generator",

  "lua-fzy",
]
