arch = [
  "7zip",
  "aria2",
  "acpi",
  "base",
  "base-devel",
  "bat",
  "bind",
  "docker",
  "docker-compose",
  "dkms",
  "dmidecode",
  "dosfstools",
  "dutree",
  "efibootmgr",
  "exfatprogs",
  "fish",
  "fisher",
  "fzf",
  "metapac",
  "git",
  "htop",
  "imagemagick",
  "inetutils",
  "libgsf",
  "linux",
  "linux-firmware",
  "linux-headers",
  "man-db",
  "mc",
  "metapac",
  "mosh",
  "nfs-utils",
  "nano",
  "ncdu",
  "sops",
  "net-tools",
  "ntp",
  "nvme-cli",
  "openvpn",
  "plocate",
  "pacman-contrib",
  "python-pynvim",
  "qt6-imageformats",
  "reflector",
  "restic",
  "rclone",
  "rsync",
  "smartmontools",
  "sshfs",
  "sudo",
  "traceroute",
  "tree",
  "tmux",
  "unrar",
  "usbutils",
  "veracrypt",
  "vi",
  "vivid",
  "vim",
  "wget",
  "whois",
  "wireless-regdb",
  "wireless_tools",
  "yay",
  "yt-dlp",
  "zram-generator",

  "hugo",

  "neovim",
  "lua-fzy",
]
