arch = [
  "alacritty",
  "android-tools",
  "arc-gtk-theme",
  "bitwarden",
  "breeze",
  "breeze-gtk",
  "breeze-plymouth",
  "feh",
  "awesome-terminal-fonts",
  "bitwarden",
  "blueman",
  "brave-bin",
  "galculator",
  "capitaine-cursors",
  "chromium",
  "copyq",
  "cups",
  "cups-pdf",
  "evince",
  "faenza-icon-theme",
  # geeqie optionally requires fbida: for jpeg rotation
  "fbida",
  "ffmpeg",
  "ffmpegthumbnailer",
  "file-roller",
  "firefox",
  "flameshot",
  "geeqie",
  "google-chrome",
  "kwalletmanager",
  "seahorse",
  "gnome-keyring",
  "gparted",
  "gvfs",
  "gvfs-mtp",
  "gvfs-nfs",
  "homebank",
  "inter-font",
  "kitty",
  "libreoffice-fresh",
  "lxappearance",
  "meld",
  "mpv",
  "network-manager-applet",
  "networkmanager",
  "nextcloud-client",
  "noto-fonts",
  "noto-fonts-emoji",
  "ntfs-3g",
  "otf-font-awesome",
  "pavucontrol",
  "poppler-data",
  "poppler-glib",
  "sddm",
  "system-config-printer",
  "thunar",
  "thunar-archive-plugin",
  "thunar-media-tags-plugin",
  "thunar-volman",
  "tigervnc",
  "tumbler",
  "ttf-bitstream-vera",
  "ttf-caladea",
  "ttf-carlito",
  "ttf-cascadia-code",
  "ttf-croscore",
  "ttf-dejavu",
  "ttf-droid",
  "ttf-fira-code",
  "ttf-fira-mono",
  "ttf-fira-sans",
  "ttf-inconsolata",
  "ttf-liberation",
  "ttf-ms-fonts",
  "ttf-opensans",
  "ttf-roboto",
  "ttf-ubuntu-font-family",
  "ttf-vista-fonts",
  "usb_modeswitch",
  "visual-studio-code-bin",
  "vlc",
  "xdg-desktop-portal",
  "xarchiver",
]
