arch = [
  "acpi",
  "base",
  "base-devel",
  "bat",
  "bind",
  "docker",
  "docker-compose",
  "dkms",
  "dmidecode",
  "dosfstools",
  "efibootmgr",
  "exfatprogs",
  "fish",
  "git",
  "htop",
  "imagemagick",
  "inetutils",
  "libgsf",
  "linux",
  "linux-firmware",
  "linux-headers",
  "man-db",
  "mc",
  "mlocate",
  "mosh",
  "nano",
  "ncdu",
  "neovim",
  "net-tools",
  "ntp",
  "pacman-contrib",
  "p7zip",
  "python-pynvim",
  "qt6-imageformats",
  "rsync",
  "smartmontools",
  "sshfs",
  "sudo",
  "tmux",
  "unrar",
  "usbutils",
  "veracrypt",
  "vi",
  "vivid",
  "vim",
  "wget",
  "whois",
  "wireless-regdb",
  "wireless_tools",
  "yay",
  "yay-debug",
  "zram-generator",
]
