arch = [
  # sway (no longer used but kept for reference)
  "sway",
  "swaylock-effects",
  "xdg-desktop-portal-wlr",

  # hyprland
  "grimblast-git",
  "hyprswitch",
  # run X clients under wayland
  "xorg-xwayland",

  # niri
  "xdg-desktop-portal-gnome",
  "xdg-desktop-portal-gtk",
  "dms-shell-bin",
  "qt6-multimedia-ffmpeg",
]
