arch = [
  # sway optionally requires foot: Terminal emulator used in the default configuration
  "foot",
  "grim",
  "slurp",
  "sway",
  "swaybg",
  "swayidle",
  "swaylock-effects",
  "waybar",
  "wdisplays",
  "wofi",
  "xdg-desktop-portal-wlr",
  # run X clients under wayland
  "xorg-xwayland",

  "wl-clipboard",
  "cliphist",

  # niri, see https://github.com/niri-wm/niri/wiki/Getting-Started
  "niri",
  "xwayland-satellite",
  "xdg-desktop-portal-gnome",
  "xdg-desktop-portal-gtk",
  "dms-shell-bin",
  "matugen",
  "cava",
  "qt6-multimedia-ffmpeg",

]
