arch = [
  # sway optionally requires foot: Terminal emulator used in the default configuration
  "foot",
  "grim",
  "slurp",
  "sway",
  "swaybg",
  "swayidle",
  "swaylock-effects",
  "waybar",
  "wdisplays",
  "wl-clipboard",
  "wofi",
  "xdg-desktop-portal-wlr",
  # run X clients under wayland
  "xorg-xwayland",
]
