arch = [
  "arandr",
  "dmenu",
  "exo",
  "garcon",
  "i3-wm",
  "i3blocks",
  "i3lock",
  "i3status",
  "numlockx",
  "rofi",
  "xfce4-appfinder",
  "xfce4-artwork",
  "xfce4-battery-plugin",
  "xfce4-clipman-plugin",
  "xfce4-cpufreq-plugin",
  "xfce4-cpugraph-plugin",
  "xfce4-dict",
  "xfce4-diskperf-plugin",
  "xfce4-eyes-plugin",
  "xfce4-fsguard-plugin",
  "xfce4-genmon-plugin",
  "xfce4-mailwatch-plugin",
  "xfce4-mount-plugin",
  "xfce4-mpc-plugin",
  "xfce4-netload-plugin",
  "xfce4-notes-plugin",
  "xfce4-notifyd",
  "xfce4-panel",
  "xfce4-power-manager",
  "xfce4-pulseaudio-plugin",
  "xfce4-screensaver",
  "xfce4-screenshooter",
  "xfce4-sensors-plugin",
  "xfce4-session",
  "xfce4-settings",
  "xfce4-smartbookmark-plugin",
  "xfce4-systemload-plugin",
  "xfce4-taskmanager",
  "xfce4-terminal",
  "xfce4-time-out-plugin",
  "xfce4-timer-plugin",
  "xfce4-verve-plugin",
  "xfce4-wavelan-plugin",
  "xfce4-weather-plugin",
  "xfce4-whiskermenu-plugin",
  "xfce4-xkb-plugin",
  # D-Bus-based configuration storage system
  "xfconf",
  # Xfce's desktop manager
  "xfdesktop",
  "xfwm4",
  "xfwm4-themes",
  "xorg-bdftopcf",
  "xorg-mkfontscale",
  "xorg-sessreg",
  "xorg-smproxy",
  "xorg-server",
  "xorg-x11perf",
  "xorg-xbacklight",
  "xorg-xcmsdb",
  "xorg-xcursorgen",
  "xorg-xdpyinfo",
  "xorg-xdriinfo",
  "xorg-xev",
  "xorg-xgamma",
  "xorg-xhost",
  "xorg-xinput",
  "xorg-xkbevd",
  "xorg-xkbprint",
  "xorg-xkbutils",
  "xorg-xkill",
  "xorg-xinit",
  "xorg-xlsatoms",
  "xorg-xlsclients",
  "xorg-xpr",
  "xorg-xrandr",
  "xorg-xrefresh",
  "xorg-xsetroot",
  "xorg-xvinfo",
  "xorg-xwd",
  "xorg-xwininfo",
  "xorg-xwud",
  # Command-line program for getting and setting the contents of the X selection
  "xsel",
  "xterm",
  "xdg-utils"
]

