replace:
  '[\\/]': _
  '^\.': _
  '[\x00-\x1f]': _
  '[<>:"\?\*\|]': _
  '\.$': _
  '\s+$': ''
  '^\s+': ''
  '^-': _
  '\ ': _

import:
  write: yes
  copy: no
  move: yes

format_item: $artist - $year - $album - $title
format_album: $albumartist - $year - $album
paths:
  default: Music/%the{$albumartist}/$year-$album%aunique{}/$track $title
  albumtype:"Audio Drama": Audio_Dramas/%the{$albumartist}/$year-$album%aunique{}/$track $title
  albumtype:"compilation": Compilations/$year-$album%aunique{}/$track $artist $title
  albumtype:"soundtrack": soundtrack/$year-$album%aunique{}/$track $artist $title


plugins: [fetchart, embedart, ftintitle, lyrics, types, lastgenre, badfiles, replaygain, the, missing, rewrite]
fetchart:
  auto: yes
embedart:
  auto: yes
  remove_art_file: yes
ftintitle:
  auto: yes
lyrics:
  auto: yes
types:
  ripped: bool
  radioplay: bool
replaygain:
  auto: no
  backend: gstreamer
rewrite:
  artist JAY-Z.*Linkin Park: Linkin Park
  artist OVERWERK*: OVERWERK
