# Backends to enable for most of metapac's behavior. See the README.md or
# run `metapac backends` for the list of backend names
enabled_backends = ["arch"]

# group files to use or to use all files in the groups folder.
# Default: false
hostname_groups_enabled = true

[arch]
package_manager = "yay"

[flatpak]
systemwide = false

# Which group files apply for which hostnames
# paths starting without a / are relative to the groups folder
# Default: None
[hostname_groups]
x1 = [
  "generic/base",
  "generic/btrfs",
  "generic/audio",
  "generic/wireless",
  "generic/xorg",
  "generic/base-ui",
  "generic/wayland",
  "generic/photography",
  "hosts/x1",
]
coolermaster = [
  "generic/base",
  "generic/btrfs",
  "generic/audio",
  "generic/wireless",
  "generic/xorg",
  "generic/base-ui",
  "generic/photography",
  "generic/virtualbox",
  "generic/latex",
  "hosts/coolermaster"
]
#server = ["example_group"]
