{ config, pkgs, lib, ... }:

{
  home.packages = with pkgs; [
    aerospace
  ];

  xdg.configFile."aerospace/aerospace.toml".text = ''
    # Generated by Home Manager
    start-at-login = true
    enable-normalization-flatten-containers = false
    enable-normalization-opposite-orientation-for-nested-containers = false
    accordion-padding = 30
    default-root-container-layout = "tiles"
    default-root-container-orientation = "auto"
    on-focused-monitor-changed = ["move-mouse monitor-lazy-center"]
    automatically-unhide-macos-hidden-apps = false

    # AeroSpace doesn't inherit the Nix profile PATH.
    # We inject the absolute Nix store paths to ensure sketchybar and borders can be found.
    # For borders, we run the Home Manager generated bordersrc script so it picks up our config options.
    after-startup-command = [
      "exec-and-forget /bin/bash -c 'PATH=${pkgs.sketchybar}/bin:${pkgs.jankyborders}/bin:$PATH sketchybar'",
      "exec-and-forget /bin/bash -c 'PATH=${pkgs.sketchybar}/bin:${pkgs.jankyborders}/bin:$PATH ~/.config/borders/bordersrc'"
    ]

    exec-on-workspace-change = [
      "/run/current-system/sw/bin/bash",
      "-c",
      "PATH=${pkgs.sketchybar}/bin:$PATH sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE"
    ]

    [key-mapping]
    preset = "qwerty"

    [gaps]
    inner.horizontal = 0
    inner.vertical = 0
    outer.bottom = 0
    outer.left = 0
    outer.right = 0
    outer.top = [{ monitor."Built-in Retina Display" = 0 }, 40]

    [mode.main.binding]
    alt-enter = "exec-and-forget open -na alacritty"
    alt-shift-q = "close --quit-if-last-window"
    alt-slash = "layout tiles horizontal vertical"
    alt-comma = "layout accordion horizontal vertical"
    alt-h = "focus left"
    alt-j = "focus down"
    alt-k = "focus up"
    alt-l = "focus right"
    alt-shift-h = "move left"
    alt-shift-j = "move down"
    alt-shift-k = "move up"
    alt-shift-l = "move right"
    alt-1 = "workspace 1"
    alt-2 = "workspace 2"
    alt-3 = "workspace 3"
    alt-4 = "workspace 4"
    alt-5 = "workspace 5"
    alt-6 = "workspace 6"
    alt-7 = "workspace 7"
    alt-8 = "workspace 8"
    alt-9 = "workspace 9"
    alt-0 = "workspace 10"
    alt-minus = "workspace 11"
    alt-equal = "workspace 12"
    alt-shift-1 = "move-node-to-workspace 1"
    alt-shift-2 = "move-node-to-workspace 2"
    alt-shift-3 = "move-node-to-workspace 3"
    alt-shift-4 = "move-node-to-workspace 4"
    alt-shift-5 = "move-node-to-workspace 5"
    alt-shift-6 = "move-node-to-workspace 6"
    alt-shift-7 = "move-node-to-workspace 7"
    alt-shift-8 = "move-node-to-workspace 8"
    alt-shift-9 = "move-node-to-workspace 9"
    alt-shift-0 = "move-node-to-workspace 10"
    alt-shift-minus = "move-node-to-workspace 11"
    alt-shift-equal = "move-node-to-workspace 12"
    cmd-h = []
    cmd-alt-h = []
    alt-f = "fullscreen"
    alt-e = "layout tiles horizontal vertical"
    alt-b = "split horizontal"
    alt-v = "split vertical"
    alt-shift-space = "layout floating tiling"
    alt-tab = "workspace-back-and-forth"
    alt-shift-tab = "move-workspace-to-monitor --wrap-around next"
    ctrl-alt-h = "workspace --wrap-around prev"
    ctrl-alt-l = "workspace --wrap-around next"
    shift-alt-backspace = "workspace-back-and-forth"
    alt-shift-semicolon = "mode service"
    alt-r = "mode resize"

    [mode.resize.binding]
    h = "resize smart -50"
    left = "resize smart -50"
    l = "resize smart +50"
    right = "resize smart +50"
    esc = ["mode main"]

    [workspace-to-monitor-force-assignment]
    1 = ["SF16T", 1]
    2 = ["SF16T", 1]
    3 = ["SF16T", "PA328", 1]
    4 = ["BenQ PD3220U", "PA328", 1]
    5 = ["BenQ PD3220U", "PA328", 1]
    6 = 2
    7 = 2
    8 = 2
    9 = 2
    10 = 2
    11 = 2

    [mode.service.binding]
    esc = ["reload-config", "mode main"]
    r = ["flatten-workspace-tree", "mode main"]
    f = ["layout floating tiling", "mode main"]
    backspace = ["close-all-windows-but-current", "mode main"]
    alt-shift-h = ["join-with left", "mode main"]
    alt-shift-j = ["join-with down", "mode main"]
    alt-shift-k = ["join-with up", "mode main"]
    alt-shift-l = ["join-with right", "mode main"]
    down = "volume down"
    up = "volume up"
    shift-down = ["volume set 0", "mode main"]
  '';
}
