{ config, pkgs, lib, ... }:

{
  xdg.configFile."borders/bordersrc" = {
    executable = true;
    text = ''
      #!/bin/bash
      # Generated by Home Manager
      options=(
        style=round
        width=6.0
        active_color=0xff0088CC
        inactive_color=0xff414550
      )
      borders "''${options[@]}"
    '';
  };
}
