arch = [
  "amd-ucode",

  "grub",
  "grub-btrfs",

  "lib32-nvidia-utils",

  "nvidia-open",
  "nvidia-settings",
  "nvtop",

  "cuda",

  "opencl-nvidia",

  "steam",
  "sunshine-git",

  "jdownloader2",

  "calibre",

  "ansible"
]
