arch = [
  "amd-ucode",

  "grub",
  "grub-btrfs",

  "lib32-nvidia-utils",

  "nvidia",
  "nvidia-settings",
  "nvtop",

  "cuda",

  "opencl-nvidia",
  "davinci-resolve",

  "steam",
  "sunshine-git",

  "lightworks",

  "jdownloader2"
]
