arch = [
  "brightnessctl",

  "grub",
  "grub-btrfs",

  # Drivers for HP DeskJet, OfficeJet, Photosmart, Business Inkjet and some LaserJet
  "hplip",

  "intel-media-driver",
  "intel-ucode",

  "libva-intel-driver",
  "mesa",

  "vulkan-intel",
  "wireguard-tools",

  # driver which allows to use the fingeprint reader as usual using fprintd
  "python-validity",
]
